import { describe, it, expect } from 'vitest';
import { ROLES, STAFF_ROLES } from '../../packages/contracts/src/generated/roles';

describe('IAM Logic & Access Checks (SUP-IAM-PANEL)', () => {
  it('validates roles structure and ensures super_admin privileges @REQ: SUP-IAM-PANEL', () => {
    const roleIds = ROLES.map(r => r.id);
    expect(roleIds).toContain('super_admin');
    expect(roleIds).toContain('org_admin');
    expect(roleIds).toContain('nurse');
    expect(roleIds).toContain('legal_guardian');
    expect(roleIds).toContain('family');

    expect(STAFF_ROLES).toContain('super_admin');
  });

  it('verifies IAM panel authorization guard @REQ: SUP-IAM-PANEL', () => {
    const isIamAllowed = (role?: string) => role === 'super_admin';

    expect(isIamAllowed('super_admin')).toBe(true);
    expect(isIamAllowed('org_admin')).toBe(false);
    expect(isIamAllowed('nurse')).toBe(false);
    expect(isIamAllowed('legal_guardian')).toBe(false);
    expect(isIamAllowed('family')).toBe(false);
    expect(isIamAllowed(undefined)).toBe(false);
  });

  it('validates audit log role_change payload shape without PII @REQ: SUP-IAM-PANEL', () => {
    const createRoleChangePayload = (targetUserId: string, newRole: string, previousRole: string) => {
      return {
        target_user_id: targetUserId,
        new_role: newRole,
        previous_role: previousRole,
        changed_at: new Date().toISOString()
      };
    };

    const payload = createRoleChangePayload('u-123', 'org_admin', 'nurse');
    const serialized = JSON.stringify(payload);

    expect(serialized).not.toMatch(/"(first_name|last_name|pesel)"/i);
    expect(payload.new_role).toBe('org_admin');
    expect(payload.previous_role).toBe('nurse');
  });

  it('validates user creation with role parameters @REQ: SUP-IAM-PANEL', () => {
    const validateCreationInput = (email: string, role: string) => {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      const validRoles = ['super_admin', 'org_admin', 'nurse', 'legal_guardian', 'family'];
      if (!email || !emailRegex.test(email)) return { valid: false, error: 'Invalid email' };
      if (!role || !validRoles.includes(role)) return { valid: false, error: 'Invalid role' };
      return { valid: true };
    };

    expect(validateCreationInput('nowy@sc.pl', 'nurse').valid).toBe(true);
    expect(validateCreationInput('nowy@sc.pl', 'super_admin').valid).toBe(true);
    expect(validateCreationInput('not-an-email', 'nurse').valid).toBe(false);
    expect(validateCreationInput('nowy@sc.pl', 'invalid_role').valid).toBe(false);
  });

  it('generates audit payload for newly created user without PII @REQ: SUP-IAM-PANEL', () => {
    const createNewUserAuditPayload = (targetUserId: string, initialRole: string) => {
      return {
        target_user_id: targetUserId,
        new_role: initialRole,
        previous_role: null,
        changed_at: new Date().toISOString()
      };
    };

    const payload = createNewUserAuditPayload('u-999', 'super_admin');
    const serialized = JSON.stringify(payload);

    expect(serialized).not.toMatch(/"(first_name|last_name|pesel|email|password)"/i);
    expect(payload.new_role).toBe('super_admin');
    expect(payload.previous_role).toBeNull();
  });

  it('validates password requirements and email normalization for IAM @REQ: SUP-IAM-PANEL', () => {
    const validatePassword = (pw?: string) => {
      if (!pw) return { valid: true, isAutoGenerated: true };
      if (pw.length < 6) return { valid: false, error: 'Password too short' };
      return { valid: true, isAutoGenerated: false };
    };

    const normalizeEmail = (e: string) => e.trim().toLowerCase();

    expect(validatePassword('123456').valid).toBe(true);
    expect(validatePassword('abc').valid).toBe(false);
    expect(validatePassword(undefined).valid).toBe(true);
    expect(validatePassword(undefined).isAutoGenerated).toBe(true);

    expect(normalizeEmail('  D.Admin@SC.PL ')).toBe('d.admin@sc.pl');
  });

  it('generates audit payload for password reset without password or PII @REQ: SUP-IAM-PANEL', () => {
    const createPasswordResetAuditPayload = (targetUserId: string) => {
      return {
        target_user_id: targetUserId,
        changed_at: new Date().toISOString()
      };
    };

    const payload = createPasswordResetAuditPayload('u-456');
    const serialized = JSON.stringify(payload);

    expect(serialized).not.toMatch(/"(password|secret|hash|token|email|first_name|last_name|pesel)"/i);
    expect(payload.target_user_id).toBe('u-456');
  });
});

